refactoring, rewriting on a class
BogdanovaMF/Job-Aggregator pull request #24
Opened 2023-04-02 18:03 UTC by BogdanovaMF

2023-04-03 03:28 UTC, g-rostislav commented on etl/main.py
> +    hh._save_data(data=data, output_filepath=OUTPUT_FILEPATH_TEMPLATE.format(source_type='hh',
по соглашению разработчиков методы начинающиеся на `_`  предназначены для внутреннего использования (конкретно здесь для внутреннего использования в классе).

Одними из принципов ООП являются абстракция и инкапсуляция.
1. Инкапсуляция - используется для сокрытия данных (чтобы никто не вызывал то, что не нужно и не обращался туда, куда не надо) посредством разделения интерфейса и реализации. Интерфейс это про то, какие кнопки нажимать, чтобы это работало (метод `save_and_parse` в нашем случае), а реализация это про то "как это работает" (`_get_links`  и прочие методы). Ну и как бы твой метод и называется `parse_and_SAVE` и логично наверно отдельно не вызывать внутренний метод `_save`, а сделать это внутри `parse_and_save` - т.е. разделяем интерфейс для взаимодействия с классом от его реализации.
2. Абстракция тоже используется для сокрытия данных, но тут только уже посредством разделения на какие-то самостоятельные юниты. В твоем примере опять же есть parse_and_save, который внутри себя должен делать и если он уже вызван, то зачем еще раз вызывать метод save? не очень логично получается

2023-04-03 03:30 UTC, g-rostislav commented on etl/clients/utils.py
> +import sys
`utils.py` общий модуль и выглядит так, как-будто будет еще где-то использоваьтся помимо модуля `clients` - поэтом предлагаю его вынести в директорию etl

2023-04-03 03:33 UTC, g-rostislav commented on etl/clients/hh.py
> +    def _save_data(self, data: List[Tuple], output_filepath: str):
Метод `save_data` (1) имеет слабую связь с самим классом и поэтому это вряд ли метод объекта класса или метод класса (подсказка - у тебя в pycharm он скорее всего подсвечивается и если навести, то он выскочет подсказка "method can be static" (метод может быть статичным - @staticmethod), т.е. он не зависит от других методов класса или объекта класса, а также от атрибутов класса или объекта класса.

Его можно было сделать просто @staticmethod, но так как функция для сохранения даннных скорее всего будет использоваться в еще других скриптах, то можно пока в какой-нибудь utils.py (уже потом если тот разрастется, то будет думать)

2023-04-03 03:36 UTC, g-rostislav commented on etl/clients/utils.py
> +logger = get_logger()
Зачем объявлять в скрипте сразу объект логгирования?
Я хочу например импортировать функцию для логгирования и в нужном месте вызывать ее и создавать объект логгирования

2023-04-03 03:36 UTC, g-rostislav commented on etl/clients/utils.py
> +logger = get_logger()
Опять же тут помимо `get_logger` будут другие еще функции и зачем мне без надобности импортировать всегда заодно и logger объект?

2023-04-03 03:38 UTC, g-rostislav commented on etl/clients/hh.py
> +    def _get_vacancy_data(cls, link: str) -> Tuple[str]:
объявляешь как `@classmethod` при этом ни разу не обращаешься к другим методом/атрибута класса

2023-04-03 03:39 UTC, g-rostislav requested changes
написал

2023-04-03 06:25 UTC, BogdanovaMF commented on etl/clients/hh.py
> +    def _get_vacancy_data(cls, link: str) -> Tuple[str]:
заменила на @staticmethod

2023-04-03 07:00 UTC, BogdanovaMF commented on etl/clients/utils.py
> +logger = get_logger()
исправлено, функцию get_logger() импортировала  в hh.py  и создала объект logger (в hh.py)

2023-04-14 06:33 UTC, g-rostislav commented on etl/utils.py
> +def save_data(data: List[Tuple], output_filepath: str):
В `utils.py` может?

2023-04-14 06:36 UTC, g-rostislav commented on main.py
> +if __name__ == '__main__':
`main.py` не соответствует своему названия (это не точка входа для запуска всего сервиса или всех скриптов). Может вынести логику в `clients/hh.py` ?

2023-04-14 06:38 UTC, g-rostislav approved these changes

2023-04-14 06:38 UTC, merged